#!/bin/sh

#
# I stress kTBS by quickly populating trace t01 with obsels
# NB: t01 should *not* have been populated before with populate-t01,
# as the would be non-monotonic.
#

dir=`dirname "$0"`
url="localhost:8001/base1/t01/"
headers="-HContent-type:text/turtle"

# TODO: add options to chose the URL?

while true; do curl $url -XPOST $headers --data-binary @$dir/obs2.ttl; done
